-- 1)List the number of films per category.
select name, count(film_id)
from category	
inner join film_category
on category.category_id=film_category.category_id
group by name

-- 2)Retrieve the store ID, city, and country for each store.
SELECT store.store_id, city.city, country.country
FROM store
inner JOIN address ON store.address_id = address.address_id
inner JOIN city ON address.city_id = city.city_id
inner JOIN country ON city.country_id = country.country_id
group by store_id


-- 3)Calculate the total revenue generated by each store in dollars.
select store.store_id, sum(amount)
from store
left join staff on store.store_id=staff.store_id
left join payment on staff.staff_id=payment.staff_id
group by store_id;

-- 4) Determine the average running time of films for each category.
select name, avg(length) from category 
left join film_category on category.category_id=film_category.category_id 
left join film on film.film_id=film_category.film_id 
group by name
